name: Flutter Golden Tests

on:
  pull_request:
    paths:
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"

permissions:
  contents: write
  pull-requests: write

jobs:
  golden_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Create base images
        run: |
          mkdir -p test/golden/counter_samples/goldens/base
          git checkout ${{ github.base_ref }}
          flutter pub get
          flutter test --update-goldens --tags=golden test/golden/counter_samples/counter_test.dart || true
          cp test/golden/counter_samples/goldens/*.png test/golden/counter_samples/goldens/base/

      - name: Create current images
        run: |
          mkdir -p test/golden/counter_samples/goldens/current
          git checkout ${{ github.head_ref }}
          flutter pub get
          flutter test --update-goldens --tags=golden test/golden/counter_samples/counter_test.dart || true
          cp test/golden/counter_samples/goldens/*.png test/golden/counter_samples/goldens/current/

      - name: Compare images
        id: compare
        run: |
          echo "Comparing images..."
          mkdir -p test/golden/counter_samples/goldens/diff
          for img in test/golden/counter_samples/goldens/base/*.png; do
            filename=$(basename "$img")
            if [ -f "test/golden/counter_samples/goldens/current/$filename" ]; then
              if ! cmp -s "$img" "test/golden/counter_samples/goldens/current/$filename"; then
                echo "Changes detected in $filename"
                echo "::set-output name=changes::true"
              fi
            fi
          done

      - name: Create or Update Comment
        uses: peter-evans/create-or-update-comment@v3
        if: always()
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Golden Test Results

            ### Initial State
            | Before | After |
            |--------|-------|
            |![Before](test/golden/counter_samples/goldens/base/signals_counter_initial.png)|![After](test/golden/counter_samples/goldens/current/signals_counter_initial.png)|

            ### After Increment
            | Before | After |
            |--------|-------|
            |![Before](test/golden/counter_samples/goldens/base/signals_counter_incremented.png)|![After](test/golden/counter_samples/goldens/current/signals_counter_incremented.png)|

            ${{ steps.compare.outputs.changes == 'true' && '⚠️ UI changes detected. Please review the changes above.' || '✅ No UI changes detected.' }}
