name: Flutter Golden Tests

on:
  pull_request:
    paths:
      - "lib/views/**"
      - "test/views/**"
      - "pubspec.yaml"

permissions:
  contents: write
  pull-requests: write

jobs:
  golden_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.0"
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            lib/views/**/*.dart

      - name: Create base images
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          git checkout ${{ github.base_ref }}
          flutter pub get
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == lib/views/* ]]; then
              test_path="test/views/$(basename ${file%.*})_test/$(basename ${file%.*})_test.dart"
              if [ -f "$test_path" ]; then
                flutter test --update-goldens "$test_path"
                mkdir -p "$(dirname $test_path)/failures"
                cp "$(dirname $test_path)/goldens/ci/"*.png "$(dirname $test_path)/failures/"
              fi
            fi
          done

      - name: Create current images
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          git checkout ${{ github.head_ref }}
          flutter pub get
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == lib/views/* ]]; then
              test_path="test/views/$(basename ${file%.*})_test/$(basename ${file%.*})_test.dart"
              if [ -f "$test_path" ]; then
                flutter test --update-goldens "$test_path"
              fi
            fi
          done

      - name: Create PR Comment
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## UI Changes Review

            以下のファイルのUI変更がありました：

            ${{ steps.changed-files.outputs.all_changed_files }}

            ### 変更内容の確認

            ${{ join(steps.changed-files.outputs.all_changed_files, '

            #### ') }}の変更：

            | 変更前 | 変更後 |
            |--------|--------|
            |![Before](test/views/my_home_page_test/failures/my_app_default_masterImage.png)|![After](test/views/my_home_page_test/goldens/ci/my_app_default.png)|

            変更内容を確認し、意図した通りの変更になっているかご確認ください。
