name: Flutter Golden Tests

on:
  pull_request:
    paths:
      - "lib/views/**"
      - "test/views/**"
      - "pubspec.yaml"

permissions:
  contents: write
  pull-requests: write

jobs:
  golden_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.27.4"
          channel: "stable"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Get changed files in this PR
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            lib/views/**/*.dart
          base_sha: ${{ github.event.pull_request.base.sha }}
          sha: ${{ github.event.pull_request.head.sha }}

      - name: Check for UI changes
        id: check-ui-changes
        run: |
          if [[ "${{ steps.changed-files.outputs.any_changed }}" != "true" ]]; then
            echo "No UI changes detected in views directory. Skipping Golden Tests."
            echo "has_ui_changes=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "UI changes detected. Proceeding with Golden Tests."
          echo "has_ui_changes=true" >> $GITHUB_OUTPUT

      - name: Create base images
        if: steps.check-ui-changes.outputs.has_ui_changes == 'true'
        run: |
          git checkout -f ${{ github.event.pull_request.base.sha }}
          flutter pub get
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == lib/views/* ]]; then
              component_name=$(basename ${file%.*})
              test_path="test/views/${component_name}_test/${component_name}_test.dart"
              test_dir="test/views/${component_name}_test"
              if [ -f "$test_path" ]; then
                echo "Running Golden Test for $component_name (base)"
                flutter test --update-goldens "$test_path"
                golden_file=$(find "$test_dir/goldens/ci" -type f -name "*.png" | head -n 1)
                if [ -n "$golden_file" ]; then
                  mkdir -p "$test_dir/failures"
                  cp "$golden_file" "$test_dir/failures/my_app_default_masterImage.png"
                else
                  echo "No golden file found for $component_name"
                  exit 1
                fi
              fi
            fi
          done

      - name: Create test images
        if: steps.check-ui-changes.outputs.has_ui_changes == 'true'
        run: |
          git checkout -f ${{ github.event.pull_request.head.sha }}
          flutter pub get
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == lib/views/* ]]; then
              component_name=$(basename ${file%.*})
              test_path="test/views/${component_name}_test/${component_name}_test.dart"
              test_dir="test/views/${component_name}_test"
              if [ -f "$test_path" ]; then
                echo "Running Golden Test for $component_name (test)"
                flutter test --update-goldens "$test_path"
                golden_file=$(find "$test_dir/goldens/ci" -type f -name "*.png" | head -n 1)
                if [ -n "$golden_file" ]; then
                  mkdir -p "$test_dir/failures"
                  cp "$golden_file" "$test_dir/failures/my_app_default_testImage.png"
                else
                  echo "No golden file found for $component_name"
                  exit 1
                fi
              fi
            fi
          done

      - name: Check for image differences
        if: steps.check-ui-changes.outputs.has_ui_changes == 'true'
        id: check-image-differences
        run: |
          has_changes=false
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == lib/views/* ]]; then
              component_name=$(basename ${file%.*})
              test_dir="test/views/${component_name}_test"
              master_image="$test_dir/failures/my_app_default_masterImage.png"
              test_image="$test_dir/failures/my_app_default_testImage.png"
              if [ -f "$master_image" ] && [ -f "$test_image" ]; then
                if ! cmp -s "$master_image" "$test_image"; then
                  has_changes=true
                  break
                fi
              fi
            fi
          done
          echo "has_image_differences=$has_changes" >> $GITHUB_OUTPUT

      - name: Commit and push images
        if: steps.check-ui-changes.outputs.has_ui_changes == 'true' && steps.check-image-differences.outputs.has_image_differences == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add test/views/*/failures/*.png
          git commit -m "test: Update Golden Test images [skip ci]" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }} || echo "No changes to push"

      - name: Generate comparison markdown
        if: steps.check-ui-changes.outputs.has_ui_changes == 'true' && steps.check-image-differences.outputs.has_image_differences == 'true'
        id: generate-markdown
        run: |
          echo "Generating comparison markdown..."
          repo_url="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.event.pull_request.head.sha }}"

          # Create a JSON array for tables
          echo "[" > tables.json
          first=true

          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == lib/views/* ]]; then
              component_name=$(basename ${file%.*})
              test_dir="test/views/${component_name}_test"
              if [ -d "$test_dir" ]; then
                if [ "$first" = true ]; then
                  first=false
                else
                  echo "," >> tables.json
                fi
                echo "{\"Component\":\"${component_name}\",\"Before\":\"![Before](${repo_url}/$test_dir/failures/my_app_default_masterImage.png?raw=true)\",\"After\":\"![After](${repo_url}/$test_dir/failures/my_app_default_testImage.png?raw=true)\"}" >> tables.json
              fi
            fi
          done
          echo "]" >> tables.json

          # Store the component names for the description
          changed_components=""
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == lib/views/* ]]; then
              component_name=$(basename ${file%.*})
              changed_components="$changed_components- $component_name\n"
            fi
          done
          echo "changed_components=$changed_components" >> $GITHUB_OUTPUT

      - name: Create comparison table
        if: steps.check-ui-changes.outputs.has_ui_changes == 'true' && steps.check-image-differences.outputs.has_image_differences == 'true'
        uses: gazab/create-markdown-table@v1
        id: create_table
        with:
          file: ./tables.json
          columns: '["Component", "Before", "After"]'

      - name: Update PR description
        if: steps.check-ui-changes.outputs.has_ui_changes == 'true' && steps.check-image-differences.outputs.has_image_differences == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get existing PR description
          existing_description=$(gh pr view ${{ github.event.pull_request.number }} --json body -q .body)

          # Generate new content for UI changes section
          new_ui_section="## UI の変更確認\n\n以下のコンポーネントのUI変更がありました：\n\n${{ steps.generate-markdown.outputs.changed_components }}\n## Golden Test の結果\n\n${{ steps.create_table.outputs.table }}\n\n変更内容を確認し、意図した通りの変更になっているかご確認ください。\n問題がなければ、\`flutter test --update-goldens --tags=golden\` を実行してGolden Imageを更新してください。"

          # Update PR description
          if [[ $existing_description == *"## UI の変更確認"* ]]; then
            # Replace existing UI changes section
            updated_description="${existing_description%%## UI の変更確認*}${new_ui_section}"
          else
            # Append new content
            updated_description="${existing_description}\n\n${new_ui_section}"
          fi

          echo -e "$updated_description" > pr_description.txt
          gh pr edit ${{ github.event.pull_request.number }} --body-file pr_description.txt

      - name: Clean up temporary files
        if: always()
        run: |
          rm -f pr_description.txt tables.json || true
